### ISSUE TITLE
troubles with readme

### ISSUE THREAD

**Issue by Gargo** [rumkin/piggy-bank#1]
>bin/connect.js Connect to running testnet with web3 and get active account.

`$ node bin/connect.js
module.js:549
    throw err;
    ^

Error: Cannot find module './lib/utils.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/oem/piggy-bank/bin/connect.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`

**Comment by rumkin** [comment]
Done.
